### ISSUE TITLE
dual fisheye remote for ISO?

### ISSUE THREAD

**Issue by GeorgeThetaZ1** [ricohapi/theta-plugins#13]
Dear friends,
I just bought theta z1. I downloaded the plugings but when i try to operate them from iphone nothing is happening.
I didint find the dual fisheye remote on apple store. is there any other way to use this pluging from iphone?
From Theta app whenever I go to pluging and says start using plungin nothing happens,
Thank you

**Comment by DaisukeHohjoh** [comment]
Hi @GeorgeThetaZ1 ,

DualFisheye Plug-in Remote is developed by Mr. Ichi Hirota not by Ricoh, and he has announced that iOS version was rejected by Apple in2020, in facebook post here. So that, at this time, you need to use Android OS phone to use this plugin remotely.
https://www.facebook.com/groups/ricoh.theta.z1/permalink/1186674711666179/

Best regards,
Daisuke Hohjoh

**Comment by GeorgeThetaZ1** [comment]
Thank you! I posted in facebook group as well but i have no answer yet. I used an Android phone and searched the dual fisheye remote but still could not find it. Can someone share a link that I can buy it?
Thank you

**Comment by DaisukeHohjoh** [comment]
Hi,

Unfortunately, DualFisheye Plug-in Remote looks not available in Google Play store anymore. It is announced by Mr. Ichi Hirota officially.
https://sites.google.com/view/h360/dualfisheye-raw

Best regards,
Daisuke Hohjoh
